#!/bin/sh

for f in *.plot ; do
  outpng="${f%.plot}.png"
  outhtml="${f%.plot}.html"
  rm -f "$outpng" "$outhtml"
done

datafiles=$(perl -wlne 'if(/\b(\w[\w-]*[.]data)\b/) { print $1 } ' mkfakedata)
rm -f fit.log $datafiles
